### ISSUE TITLE
Crash on Startup 3 seconds in 1.12.2 - 14.23.1.2555

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [HyCraftHD/Worldgeneration-Profiler#1]
Log where crash is stated
https://gist.github.com/P3rf3ctXZer0/cf84bcf0c6827663e452ec8fdad3772d

Client Latest
https://gist.github.com/P3rf3ctXZer0/916f4da5a017b1f048c989c2acb0c00c

Hmmmm

**Comment by HyCraftHD** [comment]
I see, that was my mistake. In 1.12 they repacked `IChunkGenerator` from `net.minecraft.world.chunk.IChunkGenerator` to `net.minecraft.world.gen.IChunkGenerator`
I will fix this issue soon. Thank you very much for reporting.

**Comment by HyCraftHD** [comment]
https://github.com/HyCraftHD/Worldgeneration-Profiler/commit/07894b9eb351ce166a6aceeca5ecd86234822666
Fixed with this commit.
Now combatible from 1.8 up to 1.12.2.
Release on Curseforge coming soon.
