### ISSUE TITLE
Crash on 1.12.2

### ISSUE THREAD

**Issue by jkroepke** [HyCraftHD/Worldgeneration-Profiler#2]
Hi!

I got a crash after updating to 1.1.0.

```
[19:47:53] [main/ERROR] [Worldgeneration Profiler Plugin]: CustomWorldGenerator class could not be loaded to classloader.
java.lang.ClassNotFoundException: net.hycrafthd.worldgenerationprofiler.generation.CustomWorldGenerator
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at net.hycrafthd.worldgenerationprofiler.asm.visitor.VisitorGameRegistry.insert(VisitorGameRegistry.java:65) [worldgenerationprofiler-v1.1.0.jar:1.1.0]
        at net.hycrafthd.worldgenerationprofiler.asm.visitor.VisitorGameRegistry.transform(VisitorGameRegistry.java:41) [worldgenerationprofiler-v1.1.0.jar:1.1.0]
        at net.hycrafthd.worldgenerationprofiler.asm.VisitorHelper.transform(VisitorHelper.java:33) [worldgenerationprofiler-v1.1.0.jar:1.1.0]
        at net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer.transform(Transformer.java:38) [worldgenerationprofiler-v1.1.0.jar:1.1.0]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) [ASMTransformerWrapper$TransformerWrapper.class:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_151]
        at net.minecraftforge.registries.GameData.getWrapper(GameData.java:167) [GameData.class:?]
        at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) [qe.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) [ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1458) [MinecraftServer.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.12.2-14.23.1.2581-universal.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.12.2-14.23.1.2581-universal.jar:?]
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer@1ec22831 from coremod Worldgeneration Profiler Plugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.1.2581-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 25 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/IOUtils
        at net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer.transform(Transformer.java:32) ~[worldgenerationprofiler-v1.1.0.jar:1.1.0]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.1.2581-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 25 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.IOUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        at net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer.transform(Transformer.java:32) ~[worldgenerationprofiler-v1.1.0.jar:1.1.0]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.1.2581-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        ... 25 more
```

**Comment by HyCraftHD** [comment]
I can't reproduce this crash. May you provide which forge version you used?

**Comment by jkroepke** [comment]
Forge: 14.23.1.2581

        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 4.4.0-104-generic
        Java Version: 1.8.0_151, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1708124576 bytes (1628 MB) / 2147483648 bytes (2048 MB) up to 8589934592 bytes (8192 MB)
        JVM Flags: 14 total; -Xms2G -Xmx8G -XX:MaxRAM=16G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.1.2581 171 mods loaded, 170 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State | ID                       | Version                  | Source                                                | Signature                                |
        |:----- |:------------------------ |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
        | U     | minecraft                | 1.12.2                   | minecraft.jar                                         | None                                     |
        | U     | mcp                      | 9.42                     | minecraft.jar                                         | None                                     |
        | U     | FML                      | 8.0.99.99                | forge-1.12.2-14.23.1.2581-universal.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | U     | forge                    | 14.23.1.2581             | forge-1.12.2-14.23.1.2581-universal.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | U     | ivtoolkit                | 1.3.3-1.12               | minecraft.jar                                         | None                                     |
        | UD    | solarfluxreborncore      | 3.42r                    | minecraft.jar                                         | None                                     |
        | U     | foamfixcore              | 7.7.4                    | minecraft.jar                                         | None                                     |
        | U     | woodconverter            | v2.9.2                   | [1.12]WoodConverter v2.9.2.jar                        | None                                     |
        | U     | acintegration            | 1.6.2                    | AbyssalCraft Integration-1.12.2-1.6.2.jar             | None                                     |
        | U     | abyssalcraft             | 1.9.4.3                  | AbyssalCraft-1.12.2-1.9.4.3.jar                       | None                                     |
        | U     | quarryplus               | 0.7.5                    | Additional Enchanted Miner-1.12.2-0.7.5-universal.jar | None                                     |
        | U     | ae2stuff                 | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                         | None                                     |
        | U     | applecore                | 3.1.0                    | AppleCore-mc1.12.2-3.1.0.jar                          | None                                     |
        | U     | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                            | None                                     |
        | U     | appliedenergistics2      | rv5-stable-4             | appliedenergistics2-rv5-stable-4.jar                  | None                                     |
        | U     | aroma1997core            | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                      | None                                     |
        | U     | aroma1997sdimension      | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar     | None                                     |
        | U     | circuits                 | 6.0.3                    | AutomatedRedstone-1.12.2-6.0.3.jar                    | None                                     |
        | U     | base                     | 3.5.0                    | base-1.12.2-3.5.0.jar                                 | None                                     |
        | U     | baubles                  | 1.5.1                    | Baubles-1.12-1.5.1.jar                                | None                                     |
        | U     | bdlib                    | 1.14.3.10                | bdlib-1.14.3.10-mc1.12.2.jar                          | None                                     |
        | U     | bedbugs                  | @VERSION@                | BedBugs-1.12-1.0.1.jar                                | None                                     |
        | U     | bettermuffling           | 0.1.0-Beta               | Better Muffling-1.12.2-0.1.0-Beta.jar                 | None                                     |
        | U     | betterbedrockgen         | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar                 | None                                     |
        | U     | bibliocraft              | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                     | None                                     |
        | U     | bibliotheca              | 1.2.1-1.12.2             | bibliotheca-1.2.1-1.12.2.jar                          | None                                     |
        | U     | binniecore               | unspecified              | binnie-mods-1.12.2-2.5.0.110.jar                      | None                                     |
        | U     | botany                   | 2.5.0.110                | binnie-mods-1.12.2-2.5.0.110.jar                      | None                                     |
        | U     | binniedesign             | 1.0                      | binnie-mods-1.12.2-2.5.0.110.jar                      | None                                     |
        | U     | extrabees                | 2.5.0.110                | binnie-mods-1.12.2-2.5.0.110.jar                      | None                                     |
        | U     | extratrees               | 2.5.0.110                | binnie-mods-1.12.2-2.5.0.110.jar                      | None                                     |
        | U     | genetics                 | 2.5.0.110                | binnie-mods-1.12.2-2.5.0.110.jar                      | None                                     |
        | U     | biomesoplenty            | 7.0.1.2312               | BiomesOPlenty-1.12.2-7.0.1.2312-universal.jar         | None                                     |
        | U     | bookshelf                | 2.3.518                  | Bookshelf-1.12.2-2.3.518.jar                          | None                                     |
        | U     | brandonscore             | 2.3.7                    | BrandonsCore-1.12-2.3.7.140-universal.jar             | None                                     |
        | U     | buildcraftbuilders       | 7.99.14-pre1             | buildcraft-builders-7.99.14-pre1.jar                  | None                                     |
        | U     | buildcraftcompat         | 7.99.13                  | buildcraft-compat-7.99.13.jar                         | None                                     |
        | U     | buildcraftcore           | 7.99.14-pre1             | buildcraft-core-7.99.14-pre1.jar                      | None                                     |
        | U     | buildcraftlib            | 7.99.14-pre1             | buildcraft-core-7.99.14-pre1.jar                      | None                                     |
        | U     | buildcraftenergy         | 7.99.14-pre1             | buildcraft-energy-7.99.14-pre1.jar                    | None                                     |
        | U     | buildcrafttransport      | 7.99.14-pre1             | buildcraft-transport-7.99.14-pre1.jar                 | None                                     |
        | U     | capabilityproxy          | 2.1.1                    | CapabilityProxy-1.12.2-2.1.1.jar                      | None                                     |
        | U     | cd4017be_lib             | 6.0.7                    | CD4017BE_lib-1.12.2-6.0.7.jar                         | None                                     |
        | U     | chesttransporter         | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                       | None                                     |
        | U     | chickenchunks            | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar           | None                                     |
        | U     | chisel                   | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                           | None                                     |
        | U     | clumps                   | 2.0.0                    | Clumps-3.0.0.jar                                      | None                                     |
        | U     | codechickenlib           | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar         | None                                     |
        | U     | cofhcore                 | 4.3.8                    | CoFHCore-1.12.2-4.3.8.29-universal.jar                | None                                     |
        | U     | cofhworld                | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar               | None                                     |
        | U     | comforts                 | 1.1.0                    | comforts-1.12.2-1.1.0.jar                             | None                                     |
        | U     | commoncapabilities       | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar                     | None                                     |
        | U     | cookingforblockheads     | 6.3.17                   | CookingForBlockheads_1.12.1-6.3.17.jar                | None                                     |
        | U     | craftingtweaks           | 8.1.6                    | CraftingTweaks_1.12.1-8.1.6.jar                       | None                                     |
        | U     | cultivatedtech           | 17w50-C-1.12.2           | Cultivated Tech-17w50-C-1.12.2.jar                    | None                                     |
        | U     | cyberware                | 0.2.10.2                 | cyberware-1.12.2-0.2.10.2.jar                         | None                                     |
        | U     | cyclopscore              | 0.11.0                   | CyclopsCore-1.12.2-0.11.0.jar                         | None                                     |
        | U     | darkutils                | 1.7.181                  | DarkUtils-1.12.2-1.7.181.jar                          | None                                     |
        | U     | ptrmodellib              | 1.0.0                    | Decocraft-2.5.2_1.12.2.jar                            | None                                     |
        | U     | props                    | 2.5.2                    | Decocraft-2.5.2_1.12.2.jar                            | None                                     |
        | U     | dirt2path                | 1.7.0                    | dirt2path-1.7.0.jar                                   | None                                     |
        | U     | discordintegration       | 3.0.4                    | DiscordIntegration-mc1.12.2-3.0.4.jar                 | None                                     |
        | U     | draconicevolution        | 2.3.7                    | Draconic-Evolution-1.12-2.3.7.278-universal.jar       | None                                     |
        | U     | dynmap                   | 3.0-alpha-1-3            | Dynmap-3.0-alpha-1-forge-1.12.2.jar                   | None                                     |
        | U     | dynmapblockscan          | 3.0-alpha-1-1            | DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar          | None                                     |
        | U     | enderstorage             | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar           | None                                     |
        | U     | energyconverters         | 1.0.1-buildcraft.0       | energyconverters_1.12.2-1.0.1-buildcraft.0.jar        | None                                     |
        | U     | engineersworkshop        | 1.0.3.24                 | EngineersWorkshopReborn-1.12.2-1.0.3.24.jar           | None                                     |
        | U     | environmentaltech        | 1.12.2-2.0.6b            | environmentaltech-1.12.2-2.0.6b.jar                   | None                                     |
        | U     | etlunar                  | 1.12.2-2.0.6a            | etlunar-1.12.2-2.0.6a.jar                             | None                                     |
        | U     | extracells               | 2.5.10                   | ExtraCells-1.12.2-2.5.10a47.jar                       | None                                     |
        | U     | extrautils2              | 1.0                      | extrautils2-1.12-1.7.2.jar                            | None                                     |
        | U     | bigreactors              | 1.12-0.4.5.44            | ExtremeReactors-1.12-0.4.5.44.jar                     | None                                     |
        | U     | farmingforblockheads     | 3.1.5                    | FarmingForBlockheads_1.12-3.1.5.jar                   | None                                     |
        | U     | fluxnetworks             | 3.0.2                    | fluxnetworks-1.12.2-3.0.2.jar                         | None                                     |
        | U     | foamfix                  | 0.8.3-1.12.2             | foamfix-0.8.3-1.12.2-anarchy.jar                      | None                                     |
        | U     | forestry                 | 5.7.0.219                | forestry_1.12.2-5.7.0.219.jar                         | None                                     |
        | U     | forgelin                 | 1.6.0                    | Forgelin-1.6.0.jar                                    | None                                     |
        | U     | funkylocomotion          | 1.0                      | funky-locomotion-1.12.2-1.1.0.jar                     | None                                     |
        | U     | gravestone               | 1.10.0                   | gravestone-1.10.0.jar                                 | None                                     |
        | U     | hammercore               | 1.9.5.7                  | HammerCore-1.12.2-1.9.5.7.jar                         | None                                     |
        | U     | hats                     | 7.0.0                    | Hats-1.12.2-7.0.2.jar                                 | None                                     |
        | U     | hungeroverhaul           | 1.12.2-1.3.0.jenkins131  | HungerOverhaul-1.12.2-1.3.0.jenkins131.jar            | None                                     |
        | U     | waila                    | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                             | None                                     |
        | U     | ichunutil                | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                            | None                                     |
        | U     | industrialforegoing      | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.6.5-112.jar              | None                                     |
        | U     | instantunify             | 1.1.0                    | instantunify-1.12.2-1.1.0.jar                         | None                                     |
        | U     | integrateddynamics       | 0.10.0                   | IntegratedDynamics-1.12.2-0.10.0.jar                  | None                                     |
        | U     | integrateddynamicscompat | 1.0.0                    | IntegratedDynamics-1.12.2-0.10.0.jar                  | None                                     |
        | U     | integratedtunnels        | 1.4.0                    | IntegratedTunnels-1.12.2-1.4.0.jar                    | None                                     |
        | U     | integratedtunnelscompat  | 1.0.0                    | IntegratedTunnels-1.12.2-1.4.0.jar                    | None                                     |
        | U     | integrationforegoing     | 1.12-1.4                 | IntegrationForegoing-1.12-1.4.jar                     | None                                     |
        | U     | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | None                                     |
        | U     | ironbackpacks            | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar                      | None                                     |
        | U     | ironchest                | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                       | None                                     |
        | U     | jehc                     | 1.3.1                    | jehc-1.12-1.3.1.jar                                   | None                                     |
        | U     | jei                      | 4.8.5.140                | jei_1.12.2-4.8.5.140.jar                              | None                                     |
        | U     | jeibees                  | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                          | None                                     |
        | U     | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                           | None                                     |
        | U     | kleeslabs                | 5.3.2                    | KleeSlabs_1.12-5.3.2.jar                              | None                                     |
        | U     | laggoggles               | 2.0                      | LagGoggles-1.12.2-2.0.jar                             | None                                     |
        | U     | levelup2                 | ${version}               | Level Up! 2-1.1.14-1.12.jar                           | None                                     |
        | U     | login_shield             | 1.12.2-1-g24c2a5e        | Login_Shield-1.12.2-1-g24c2a5e.jar                    | None                                     |
        | U     | lostcities               | 1.0.2                    | lostcities-1.12-1.0.2.jar                             | None                                     |
        | U     | magicbees                | 1.0                      | MagicBees-1.12-3.1.7.jar                              | None                                     |
        | U     | malisiscore              | 1.12.2-6.3.0             | malisiscore-1.12.2-6.3.0.jar                          | None                                     |
        | U     | malisisdoors             | 1.12.2-7.2.2             | malisisdoors-1.12.2-7.2.2.jar                         | None                                     |
        | U     | malisisswitches          | 1.12-5.0.0               | malisisswitches-1.12-5.0.0.jar                        | None                                     |
        | U     | mantle                   | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                              | None                                     |
        | U     | mcmultipart              | 2.4.1                    | MCMultiPart-2.4.1.jar                                 | None                                     |
        | U     | mekanism                 | 1.12.2-9.4.3.330         | Mekanism-1.12.2-9.4.3.330.jar                         | None                                     |
        | U     | mekanismgenerators       | 9.4.3                    | MekanismGenerators-1.12.2-9.4.3.330.jar               | None                                     |
        | U     | mekanismtools            | 9.4.3                    | MekanismTools-1.12.2-9.4.3.330.jar                    | None                                     |
        | U     | mercurius_updater        | 1.0                      | MercuriusUpdater-1.12.2.jar                           | None                                     |
        | U     | testdummy                | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                            | None                                     |
        | U     | mob_grinding_utils       | 0.3.4                    | MobGrindingUtils-0.3.4.jar                            | None                                     |
        | U     | modularrouters           | 1.12.1-3.0.3             | modular-routers-1.12.1-3.0.3.jar                      | None                                     |
        | U     | morebees                 | 1.12.2-1.4.4             | morebees-1.12.2-1.4.4.jar                             | None                                     |
        | U     | morpheus                 | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                               | None                                     |
        | U     | nex                      | 2.1.14.15                | NetherEx-1.12-2.1.14.15.jar                           | None                                     |
        | U     | netherportalfix          | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar                     | None                                     |
        | U     | nmsot                    | 1.2.1-mc1.12             | NoMobSpawningOnTrees-1.2.1-mc1.12.jar                 | None                                     |
        | U     | nei                      | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar         | None                                     |
        | U     | p455w0rdslib             | 2.0.24                   | p455w0rdslib-1.12-2.0.24.jar                          | None                                     |
        | U     | harvestcraft             | 1.12.2b                  | Pam's HarvestCraft 1.12.2b - Re-Balance Update.jar    | None                                     |
        | U     | plustic                  | 6.3.2.1                  | plustic-6.3.2.1.jar                                   | None                                     |
        | U     | quantumstorage           | 4.4.6                    | QuantumStorage-1.12-4.4.6.jar                         | None                                     |
        | U     | quickhomes               | 1.2                      | QuickHomes-1.2.jar                                    | None                                     |
        | U     | quickleafdecay           | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                     | None                                     |
        | U     | randomthings             | 4.1                      | RandomThings-MC1.12.2-4.1.jar                         | None                                     |
        | U     | reborncore               | 3.5.2.171                | RebornCore-1.12.2-3.5.2.171-universal.jar             | None                                     |
        | U     | reccomplex               | 1.4.6                    | RecurrentComplex-1.4.6.jar                            | None                                     |
        | U     | redstoneflux             | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar               | None                                     |
        | U     | redstonepaste            | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                        | None                                     |
        | U     | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                    | None                                     |
        | U     | signal-catcher           | 1.1                      | signalcatcher-1.1.jar                                 | None                                     |
        | U     | simpleportals            | 1.12.2-1.5.1.0           | simpleportals-1.12.2-1.5.1.0.jar                      | None                                     |
        | U     | simplyjetpacks           | 2.2.1.20                 | SimplyJetpacks2-1.12.2-2.2.1.20.jar                   | None                                     |
        | U     | sodiumcraft              | 1.3.2                    | sodiumcraft-1.3.2.jar                                 | None                                     |
        | U     | solarfluxreborn          | 3.42r                    | SolarFluxReborn_1.12.2-3.42r.jar                      | None                                     |
        | U     | sonarcore                | 5.0.4                    | sonarcore-1.12.2-5.0.4.jar                            | None                                     |
        | U     | spiceoflife              | 1.3.11                   | SpiceOfLife-mc1.12-1.3.11.jar                         | None                                     |
        | U     | stevescarts              | ${version}               | StevesCarts-1.12.2-2.4.13.69.jar                      | None                                     |
        | U     | tconstruct               | 1.12-2.8.1.49            | TConstruct-1.12-2.8.1.49.jar                          | None                                     |
        | U     | tesla                    | 1.0.60                   | Tesla-1.12-1.0.60.jar                                 | None                                     |
        | U     | teslacorelib_registries  | 1.0.12                   | tesla-core-lib-1.12-1.0.12.jar                        | None                                     |
        | U     | teslacorelib             | 1.0.12                   | tesla-core-lib-1.12-1.0.12.jar                        | None                                     |
        | U     | beneath                  | 1.3.0                    | The Beneath-1.12.2-1.3.0.jar                          | None                                     |
        | U     | thermalcultivation       | 0.1.3                    | ThermalCultivation-1.12.2-0.1.3.11-universal.jar      | None                                     |
        | U     | thermaldynamics          | 2.3.8                    | ThermalDynamics-1.12.2-2.3.8.16-universal.jar         | None                                     |
        | U     | thermalexpansion         | 5.3.9                    | ThermalExpansion-1.12.2-5.3.9.6-universal.jar         | None                                     |
        | U     | thermalfoundation        | 2.3.8                    | ThermalFoundation-1.12.2-2.3.8.22-universal.jar       | None                                     |
        | U     | tickprofiler             | 1.12-0.0.2               | TickProfiler-1.12-0.0.2.jar                           | None                                     |
        | U     | tinkegration             | 0.1.1                    | tinkegration-0.1.1.jar                                | None                                     |
        | U     | tinker_io                | release 2.5.6e           | tinker_io-1.12-release 2.5.6e.jar                     | None                                     |
        | U     | tinkersaddons            | 1.0.7                    | Tinkers' Addons-1.12.1-1.0.7.jar                      | None                                     |
        | U     | tinkertoolleveling       | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar                     | None                                     |
        | U     | torchmaster              | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                       | None                                     |
        | U     | treechopper              | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                          | None                                     |
        | U     | twilightforest           | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar           | None                                     |
        | U     | unidict                  | 1.12.2-2.0               | UniDict-1.12.2-2.0.jar                                | None                                     |
        | U     | usefulnullifiers         | 1.4.1                    | usefulnullifiers-1.4.1.jar                            | None                                     |
        | U     | valkyrielib              | 1.12.2-2.0.6b            | valkyrielib-1.12.2-2.0.6b.jar                         | None                                     |
        | U     | wanionlib                | 1.12.2-1.4               | WanionLib-1.12.2-1.4.jar                              | None                                     |
        | U     | waterstrainer            | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                          | None                                     |
        | U     | wawla                    | 2.5.246                  | Wawla-1.12.2-2.5.246.jar                              | None                                     |
        | U     | wct                      | 3.8.55                   | WirelessCraftingTerminal-1.12.2-3.8.55.jar            | None                                     |
        | U     | woot                     | 1.12.2-0.0.4             | woot-1.12.2-0.0.4.jar                                 | None                                     |
        | U     | xnet                     | 1.6.3                    | xnet-1.12-1.6.3.jar                                   | None                                     |
        | U     | xtones                   | 1.12-1.0.7-10            | Xtones-1.12-1.0.7-10.jar                              | None                                     |
        | U     | zerocore                 | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                             | None                                     |


Note: Its a mod list from an other crash report.

**Comment by HyCraftHD** [comment]
Thanks for the information. I think this seems to be a problem on linux systems, as it seems that the compiled files are not loaded correcly to vm. I hope i can fix this issue soon.

**Comment by HyCraftHD** [comment]
Please Update to 1.1.1. Then this issue should be solved.
