### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by TheUntamed** [HyCraftHD/Worldgeneration-Profiler#7]
I put together a modpack (mc 1.15.2 with Forge 31.1.30) and chunks are not loaded.
I have this mod installed (version 1.3.0.6) but i'm not getting any notifications.
I'm on a single player world and have no server console. I read the documentation and I suppose with client console you mean the chat ingame?
![2020-03-29_23 35 08](https://user-images.githubusercontent.com/48363903/77861862-ef21b780-7217-11ea-8ed4-f96f11dc7e80.png)

**Comment by HyCraftHD** [comment]
No its in the log. In your minecraft console log if you have it enabled or in the file logs/latest.log or logs/worldgenprofiler.log

**Comment by TheUntamed** [comment]
oh ok, my fault. Thank you
